//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlatformTextEditorCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPlatformTextEditorCore.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v4.3.1 (https://getbootstrap.com/)
        /// * Copyright 2011-2019 The Bootstrap Authors
        /// * Copyright 2011-2019 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#dc3545;--orange:#fd7e14;--yellow:#ffc107;--green:#28a745;--teal:#20c997;--cyan:#17a2b8;--white:#fff;--gray:#6c757d;--gray-dark:#343a40;--primary:#007bff;--secondary:#6c757d;--success:#28a745;--info:#17a2b8;--warning [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _css_bootstrap_min_css {
            get {
                return ResourceManager.GetString("/css/bootstrap.min.css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///html {
        ///  font-size: 16px;
        ///}
        ///@media (min-width: 768px) {
        ///  html {
        ///    font-size: 16px;
        ///  }
        ///}
        ///
        ///body &gt; div {
        ///    position: absolute;
        ///    left: 0;
        ///    top: 0;
        ///    width: 100%;
        ///    height: 100%;
        ///    display: grid;
        ///    overflow: hidden;
        ///    grid-template-rows: 58px auto;
        ///    grid-template-areas: &apos;header&apos; &apos;editor&apos;;
        ///}
        ///
        ///nav {
        ///    grid-area: header;
        ///}
        ///nav p, nav span {
        ///    cursor: default;
        ///    display: inline;
        ///    margin-bottom: -5px !important;
        ///}
        ///textarea {
        ///    grid-area: editor;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _css_site_css {
            get {
                return ResourceManager.GetString("/css/site.css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _favicon_ico {
            get {
                object obj = ResourceManager.GetObject("/favicon.ico", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;link rel=&quot;icon&quot; type=&quot;image/x-icon&quot; href=&quot;favicon.ico&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/bootstrap.min.css&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/site.css&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body class=&quot;bg-secondary&quot;&gt;
        ///
        ///&lt;div&gt;
        ///    &lt;nav class=&quot;navbar navbar-expand-md navbar-dark bg-dark&quot;&gt;
        ///        &lt;div class=&quot;container&quot;&gt;
        ///            &lt;div&gt;
        ///                &lt;div&gt;
        ///                    &lt;p class=&quot;h5 tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _index_html {
            get {
                return ResourceManager.GetString("/index.html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (async function() {
        ///
        ///    const apiUrl = &quot;api/file&quot;;
        ///    const title = document.getElementById(&quot;title&quot;);
        ///    const subTitle = document.querySelector(&quot;span.small&quot;);
        ///    const save = document.getElementById(&quot;save&quot;);
        ///    const editor = document.getElementById(&quot;editor&quot;);
        ///    const badge = document.querySelector(&quot;.badge&quot;);
        ///    badge.style[&quot;display&quot;] = &quot;none&quot;;
        ///
        ///    const response = await fetch(apiUrl);
        ///    const name = response.headers.get(&quot;x-file-name&quot;);
        ///    const fullName = response.headers.get(&quot;x-fu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _js_site_js {
            get {
                return ResourceManager.GetString("/js/site.js", resourceCulture);
            }
        }
    }
}
